# Generated by Django 5.2.8 on 2025-11-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_name", models.CharField(max_length=50)),
                ("emp_id", models.IntegerField(unique=True)),
                ("emp_designation", models.CharField(max_length=30)),
            ],
        ),
    ]
